Datasource datadog user
DataDog/terraform-provider-datadog pull request #1124
Opened 2021-06-24 15:06 UTC by tleveque69

Introducing a datasource to retrieve datadog user using their email

2021-06-30 15:21 UTC, zippolyte requested changes
You'll also need to rebase on top of master. There have been changes in the go client version, and the API for making requests changed a bit.
The terraform plugin SDK v2 is also used, and the signature of the read function is a little different, it return diagnostics, and takes a context as first argument too

2021-06-30 15:21 UTC, zippolyte commented on datadog/data_source_datadog_user.go
> +	founded := false
grammar nit:
```suggestion
	found := false
```

2021-06-30 15:21 UTC, zippolyte commented on datadog/data_source_datadog_user.go
> +		return fmt.Errorf("didn't found any user mathing this email")
```suggestion
		return fmt.Errorf("didn't find any user matching filter string  \"%s\"", )
```

2021-06-30 15:21 UTC, zippolyte commented on datadog/data_source_datadog_user.go
> +				Description: "email",
Filter all users by the given string.

2021-06-30 15:21 UTC, zippolyte commented on datadog/internal/utils/utils.go
> -func TranslateClientError(err error, apiURL *url.URL, msg string) error {
let's not change that

2021-06-30 15:21 UTC, zippolyte commented on datadog/data_source_datadog_user.go
> +	}
Let's not go through all the pages. Instead if there is more than one result (i.e. `total_filtered_count > 1`, return an error stating that there's more than one user matching the filter, and that it should be refined.
Similar to what we do in other datasources, like role http://github.com/datadog/terraform-provider-datadog/blob/master/datadog/data_source_datadog_role.go#L67-L71

2021-08-05 07:03 UTC, tleveque69 commented
I haven't been able to record the tests because of the following error eventhough i did what was mention (multiple times).
I used a trial version of DD on which i am admin  

`The keys you've set potentially belong to a production environment. Tests do all sorts of create/update/delete calls to the organisation, so only run them against a sandbox environment. If you know what you are doing, set the DD_TEST_ORG environment variable to the public ID of your organization. See https://docs.datadoghq.com/api/latest/organizations/#list-your-managed-organizations to get it.`

2021-08-05 13:44 UTC, zippolyte requested changes
Left some more comments.
If you're having issues with recording, I can run it and push to your branch when you've addressed the comments

2021-08-05 13:44 UTC, zippolyte commented on datadog/tests/data_source_datadog_user_test.go
> +	}`, uniq)
you will need to add the config for the resource here, and add a `depends_on` in the datasource piece when you switch to a unique username

2021-08-06 13:38 UTC, tleveque69 commented
I'm sorry i left so much unused code in this PR thank you so much for you review :pray: .

I tried to correct the test using your advices however can't really test them because of the previous error if u have a workaround or can record them i'll be glad :+1:

2021-08-06 15:54 UTC, zippolyte commented
/azp run

2021-08-06 15:54 UTC, zippolyte approved these changes

2021-08-09 07:25 UTC, merged