Fixed Terraform examples for  `datadog_integration_aws_log_collection/tag_filter`
DataDog/terraform-provider-datadog pull request #1127
Opened 2021-06-25 07:59 UTC by magnetikonline

Noted in the public docs a small typo for resources:

- `datadog_integration_aws_log_collection`
- `datadog_integration_aws_tag_filter`

This should fix the typos on next documentation generate.

2021-06-29 13:57 UTC, therve commented
Thanks for your patch! Could you run `make docs`? This will updated the generated docs and then I can merge it directly.

2021-06-30 03:00 UTC, magnetikonline commented
Will do @therve - sorry I thought maybe this took place during a GitHub Actions build. Leave it with me 👍

2021-06-30 14:57 UTC, zippolyte requested changes
Thanks for the PR, you'll just need to run `make docs` to regenerate the documentation and include the updates

2021-06-30 14:58 UTC, zippolyte commented
Oops sorry for the noise, didn't see therve already posted this 😬

2021-07-01 02:43 UTC, magnetikonline commented
hehe - not a problem @zippolyte - thx for reaching out 👍 

@therve have run `make docs` and committed the updates against d314698.

2021-07-01 08:20 UTC, merged

2021-07-02 01:08 UTC, magnetikonline commented
Thanks @zippolyte 👍