[SMD-565] - terraform support filter source
DataDog/terraform-provider-datadog pull request #1142
Opened 2021-07-13 10:53 UTC by adussarps

This PR adds supports into terraform for the list filter endpoint. 

It adds a new source that allow a user to list filters for it's organisation.

2021-07-21 20:01 UTC, jtappa submitted a review, later dismissed

2021-07-22 07:02 UTC, therve requested changes
Resource look good, PR contains all the previous changes and conflicts, can you rebase? Thanks.

2021-07-22 18:07 UTC, jtappa approved these changes

2021-07-23 12:19 UTC, therve approved these changes

2021-07-23 12:19 UTC, therve commented
/azp run

2021-07-23 12:39 UTC, merged