Add new_group_delay monitor option
DataDog/terraform-provider-datadog pull request #1176
Opened 2021-08-18 18:58 UTC by chrismdd

This PR adds a new monitor option, `new_group_delay` to the monitor data source and resource.

`new_group_delay` is a replacement for `new_host_delay` that works for all multi-alert monitors, not only for those grouped by host. When both options are specified in a monitor definition, `new_group_delay` overrides `new_host_delay`.

`new_host_delay` currently defaults to 300 in this provider. Removing this default would be a breaking change and is therefore not possible without a major version update.

The ideal behavior would be for `new_group_delay` and `new_host_delay` to conflict with each other, and for the provider to not set a default value for `new_host_delay` when `new_group_delay` is specified in the config of a monitor resource. Unfortunately, due to limitations of the terraform SDK, it is not possible (as far as I can tell) to reliably distinguish between `new_group_delay` being set to zero in the config and not being set at all. Specifically, I found that it wasn't possible to unset this field in `updateMonitorState` because `ResourceData` stores fields in multiple levels that are merged when reading the field, but we can only unset the field at one level.

Instead, we opted to keep `new_group_delay` and `new_host_delay` independent. This has the downside that disabling delay for monitors grouped by by host requires setting `new_host_delay` to zero, despite the field now being deprecated. This requirement is clearly documented.

2021-08-18 21:54 UTC, alai97 requested changes
Minor wording nit!

2021-08-18 21:54 UTC, alai97 commented on docs/resources/monitor.md
> +new_group_delay overrides new_host_delay if it is set to a nonzero value.
```suggestion
`new_group_delay` overrides `new_host_delay` if it is set to a nonzero value.
```

2021-08-18 21:54 UTC, alai97 commented on docs/resources/monitor.md
> +To disable group delay for monitors grouped by host, new_host_delay must be set to zero due to the default value of 300 for that field (new_group_delay defaults to zero, so setting it to zero is not
```suggestion
To disable group delay for monitors grouped by host, `new_host_delay` must be set to zero due to the default value of 300 for that field (`new_group_delay` defaults to zero, so setting it to zero is not required).
```

2021-08-18 21:54 UTC, alai97 commented on docs/resources/monitor.md
> +- **new_host_delay** (Number, Deprecated) Time (in seconds) to allow a host to boot and applications to fully start before starting the evaluation of monitor results. Should be a non negative integer
```suggestion
- **new_host_delay** (Number, Deprecated) Time (in seconds) to allow a host to boot and applications to fully start before starting the evaluation of monitor results. Should be a non-negative integer. Defaults to `300` (this default will be removed in a major version release and new_host_delay will be removed entirely in a subsequent major version release). **Deprecated.** Prefer using `new_group_delay` (except when setting `new_host_delay` to zero).
```

2021-08-19 09:44 UTC, zippolyte approved these changes

2021-08-19 09:45 UTC, zippolyte commented
/azp run

2021-08-20 12:43 UTC, zippolyte commented
/azp run

2021-08-20 12:43 UTC, zippolyte approved these changes

2021-08-20 13:39 UTC, merged

2022-02-09 19:16 UTC, jasperbogers-ig commented
This change does not appear to work as a replacement for new_host_delay; we see an error `{"errors": ["The new_group_delay option can only be used for multi-alert monitors"]}`, breaking our build.