docs: Update docs for rrule/type
DataDog/terraform-provider-datadog pull request #1434
Opened 2022-05-03 16:07 UTC by mikebryant

I got a bit stuck getting this to work until I read the source. Updating the docs here to make it clear how to use rrule

2022-05-03 22:00 UTC, buraizu requested changes
Small edit for consistency

2022-05-03 22:08 UTC, mikebryant commented on docs/resources/downtime.md
> +- **type** (String) One of `days`, `weeks`, `months`, `years`, or `rrule`
Cheers, done :)

2022-05-03 22:13 UTC, buraizu submitted a review, later dismissed

2022-05-13 19:08 UTC, skarimo commented
Could you rebase on master and regenerate new docs. Thanks!

2022-05-13 22:11 UTC, mikebryant commented
@skarimo done :)

2022-05-16 13:49 UTC, merged