[Workflows] Add run-workflow widget definition to dashboard resource
DataDog/terraform-provider-datadog pull request #1779
Opened 2023-02-15 19:47 UTC by DavidRobertAnsart

## Changes

- Add run workflow widget definition to dashboard resource.
- Add test and recorded cassettes for the new widget.
- Add doc.

## How to test:

1. Build the provider locally.
2. Try this dashboard:
```tf
resource "datadog_dashboard" "ordered_dashboard" {
  title       = "Run workflow terraform dashboard"
  layout_type = "ordered"
  template_variable {
    name             = "Env"
    prefix           = "Env"
    defaults         = ["*"]
    available_values = ["prod", "staging", "test"]
  }
  widget {
    run_workflow_definition {
      title       = "My workflow widget"
      title_size  = "13"
      title_align = "left"
      workflow_id = "2e055f16-8b6a-4cdd-b452-17a34c44b160"
      input {
        name  = "env"
        value = "$Env.value"
      }
    }
    widget_layout {
      x      = 0
      y      = 0
      width  = 4
      height = 4
    }
  }
  notify_list = []
  reflow_type = "fixed"
}
```

2023-02-15 20:52 UTC, nkzou submitted a review, later dismissed

2023-02-15 22:17 UTC, cswatt requested changes
small nitpicky things

2023-02-15 22:17 UTC, cswatt commented on docs/resources/dashboard.md
> +- `override_label` (String) The label id that refers to a context menu link item. When override_label is provided, the client request omits the label field.
```suggestion
- `override_label` (String) The label ID that refers to a context menu link item. When `override_label` is provided, the client request omits the label field.
```

2023-02-15 22:17 UTC, cswatt commented on docs/resources/dashboard.md
> +- `value` (String) Dashboard template variable. Can be suffixed with '.value' or '.key'.
```suggestion
- `value` (String) Dashboard template variable. Can be suffixed with `.value` or `.key`.
```

2023-02-15 22:17 UTC, cswatt commented on docs/resources/dashboard.md
> +- `workflow_id` (String) Workflow id
```suggestion
- `workflow_id` (String) Workflow ID
```

2023-02-15 22:17 UTC, cswatt commented on docs/resources/dashboard.md
> +- `workflow_id` (String) Workflow id
```suggestion
- `workflow_id` (String) Workflow ID
```

2023-02-15 22:17 UTC, cswatt commented on docs/resources/dashboard.md
> +- `override_label` (String) The label id that refers to a context menu link item. When override_label is provided, the client request omits the label field.
```suggestion
- `override_label` (String) The label ID that refers to a context menu link item. When `override_label` is provided, the client request omits the label field.
```

2023-02-15 22:17 UTC, cswatt commented on docs/resources/dashboard.md
> +- `value` (String) Dashboard template variable. Can be suffixed with '.value' or '.key'.
```suggestion
- `value` (String) Dashboard template variable. Can be suffixed with `.value` or `.key`.
```

2023-02-16 19:14 UTC, skarimo approved these changes

2023-02-16 21:44 UTC, DrkSephy approved these changes
Thanks for this contribution 🙌

2023-02-16 22:07 UTC, cswatt approved these changes

2023-02-16 22:21 UTC, merged