[datadog_team] Add datadog team data sources
DataDog/terraform-provider-datadog pull request #1946
Opened 2023-06-01 19:36 UTC by skarimo

This PR adds the following 2 data sources:

- datadog_team
- datadog_team_memberships

This is a follow up to: https://github.com/DataDog/terraform-provider-datadog/pull/1908

2023-06-01 19:55 UTC, nkzou requested changes

2023-06-01 19:55 UTC, nkzou commented on datadog/fwprovider/data_source_datadog_team_memberships.go
> +		if len(ddResp.GetData()) == 0 || len(ddResp.GetData()) < 100 {
```suggestion
		if len(ddResp.GetData()) < 100 {
```

2023-06-01 19:55 UTC, nkzou commented on datadog/fwprovider/data_source_datadog_team.go
> +		Description: "Use this data source to retrieve information about an existing api key.",
```suggestion
		Description: "Use this data source to retrieve information about an existing Datadog team.",
```

2023-06-01 19:55 UTC, nkzou commented on datadog/fwprovider/data_source_datadog_team_memberships.go
> +		Description: "Use this data source to retrieve information about an existing api key.",
```suggestion
		Description: "Use this data source to retrieve information about an existing Datadog team membership.",
```

2023-06-01 19:55 UTC, nkzou commented on datadog/fwprovider/data_source_datadog_team_memberships.go
> +				Description: "Free-form markdown description/content for the team's homepage.",
Is this description right? Doesn't seem to match

2023-06-02 09:44 UTC, KrisKennawayDD approved these changes

2023-06-02 09:44 UTC, KrisKennawayDD commented on datadog/fwprovider/data_source_datadog_team.go
> +				Description: "The team's identifier",
nit: s/identifier/handle/

2023-06-05 15:40 UTC, eric-wood approved these changes
This looks good to me!

2023-06-05 18:28 UTC, merged