[ip_allow_list]Migrate ip allow list to framework
DataDog/terraform-provider-datadog pull request #2239
Opened 2024-01-11 16:14 UTC by HantingZhang2

SSIA

2024-01-11 17:27 UTC, estherk15 submitted a review, later dismissed

2024-01-11 21:32 UTC, nkzou requested changes

2024-01-11 21:32 UTC, nkzou commented on datadog/fwprovider/resource_datadog_ip_allowlist.go
> +
```suggestion
```
This function seems unused

2024-01-12 14:28 UTC, nkzou approved these changes

2024-01-12 14:57 UTC, merged