[rum_metric] Add support
DataDog/terraform-provider-datadog pull request #2643
Opened 2024-11-04 16:28 UTC by hemeryar

Adds terraform support for RUM custom metrics.

https://datadoghq.atlassian.net/browse/RUM-5984

2024-11-14 16:06 UTC, cswatt requested changes

2024-11-14 16:06 UTC, cswatt commented on docs/resources/rum_metric.md
> +- `name` (String) The name of the rum-based metric. This field can't be updated after creation.
```suggestion
- `name` (String) The name of the RUM-based metric. This field can't be updated after creation.
```

2024-11-14 16:21 UTC, hemeryar commented on docs/resources/rum_metric.md
> +- `name` (String) The name of the rum-based metric. This field can't be updated after creation.
Done

2024-11-14 16:22 UTC, hemeryar commented on docs/resources/rum_metric.md
> +- `path` (String) The path to the value the rum-based metric will aggregate on. Only present when `aggregation_type` is `distribution`.
Done

2024-11-14 16:22 UTC, hemeryar commented on docs/resources/rum_metric.md
> +- `query` (String) The search query - following the RUM search syntax.
Done

2024-11-14 16:22 UTC, hemeryar commented on docs/resources/rum_metric.md
> +- `path` (String) The path to the value the rum-based metric will be aggregated over.
Done

2024-11-14 16:22 UTC, hemeryar commented on docs/resources/rum_metric.md
> +- `tag_name` (String) Eventual name of the tag that gets created. By default, `path` is used as the tag name.
Done

2024-11-14 16:23 UTC, cswatt submitted a review, later dismissed

2024-11-15 19:11 UTC, amaskara-dd submitted a review, later dismissed

2024-11-18 11:43 UTC, HantingZhang2 approved these changes

2024-11-18 11:44 UTC, merged