scaffold app in tf provider
DataDog/terraform-provider-datadog pull request #2723
Opened 2024-12-16 22:14 UTC by tyffical

2025-01-13 19:45 UTC, tyffical commented
* **#2723** <a href="https://app.graphite.dev/github/pr/DataDog/terraform-provider-datadog/2723?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈 <a href="https://app.graphite.dev/github/pr/DataDog/terraform-provider-datadog/2723?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `master`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
<!-- Current dependencies on/for this PR: -->

2025-02-06 18:35 UTC, embeaken reviewed
great work!

2025-02-06 18:35 UTC, embeaken commented on datadog/fwprovider/data_source_datadog_app.go
> +	response.TypeName = "app"
maybe worth naming the resource `app_builder_app` across this PR since `app` is such an overloaded word

2025-02-06 18:35 UTC, embeaken commented on datadog/fwprovider/framework_provider.go
> +	// Enable unstable operations for the App Builder API
before public release let's make sure the endpoints are on `v2`

2025-02-06 18:35 UTC, embeaken commented on datadog/fwprovider/resource_datadog_app.go
> +			// error body may have useful info for the user
just an observation from my testing - you should make sure your API doesn't expose any internal errors or they will show up in TF errors as well

2025-02-06 18:35 UTC, embeaken commented on datadog/fwprovider/resource_datadog_app.go
> +	err := json.Unmarshal([]byte(appModel.AppJson.String()), &appJsonString)
In providers, you should use `ValueString()` to get a string instead of `String()` which is for debugging. when i used `String()` it made the strings all double-quoted

this comment applies to all usage of `String()` in this PR

2025-02-06 18:35 UTC, embeaken commented on datadog/fwprovider/resource_datadog_app.go
> +	// decode encoded json into string and then decode that into the attributes struct
do you need two `Unmarshal`s here? Seems like you could just do

```
err = json.Unmarshal([]byte(plan.AppJson.ValueString()), attributes)
```

2025-02-06 18:50 UTC, drichards-87 approved these changes
Left some suggestions from the Docs and approved the PR.

2025-02-06 18:50 UTC, drichards-87 commented on docs/data-sources/app.md
> +  Use this data source to retrieve information about an existing Datadog App from the App Builder product, for use in other resources.
```suggestion
  Use this data source to retrieve information about an existing Datadog App from App Builder for use in other resources.
```

2025-02-06 18:50 UTC, drichards-87 commented on docs/data-sources/app.md
> +Use this data source to retrieve information about an existing Datadog App from the App Builder product, for use in other resources.
```suggestion
Use this data source to retrieve information about an existing Datadog App from App Builder for use in other resources.
```

2025-02-06 18:50 UTC, drichards-87 commented on docs/data-sources/app.md
> +  Use this data source to retrieve information about an existing Datadog App from the App Builder product, for use in other resources.
An alternative suggestion to avoid using the word "Use" twice in the same sentence: "This data source retrieves information about an existing Datadog App from App Builder for use in other resources."

2025-02-06 18:50 UTC, drichards-87 commented on docs/resources/app.md
> +  Provides a Datadog App resource. This can be used to create and manage a Datadog App from the App Builder product.
```suggestion
  Provides a Datadog App resource for creating and managing Datadog Apps from App Builder.
```

2025-02-06 18:50 UTC, drichards-87 commented on docs/resources/app.md
> +Provides a Datadog App resource. This can be used to create and manage a Datadog App from the App Builder product.
```suggestion
Provides a Datadog App resource for creating and managing Datadog Apps from App Builder.
```

2025-02-06 18:50 UTC, drichards-87 commented on docs/resources/app.md
> +# Example app json - loaded from a file (necessary if includes ${} syntax)
```suggestion
# Example app JSON - loaded from a file (required for ${} syntax)
```

2025-02-07 00:34 UTC, oliverli reviewed
Looks great! I don't have much more to add beyond what Ilya has already covered

Strongly in favor of naming the resource `datadog_app_json` so that we have the option of creating a new `datadog_app` resource in the future with higher level CDK style mechanics, especially more so since dashboards has `datadog_dashboard_json` so we'll be in line with them

2025-03-20 19:52 UTC, drichards-87 submitted a review, later dismissed

2025-03-21 18:10 UTC, GabeWM commented on datadog/fwprovider/data_source_datadog_app_builder_app.go
> +				Description: "Whether the app is published or unpublished. Published apps are available to other users. To ensure the app is accessible to the correct users, you also need to set a [Restriction P
One caveat on the restriction policies is they do not currently support scoped keys. Yet we require scoped keys. So this could be really tedious for a customer. Just calling this out.

2025-03-21 18:12 UTC, tyffical commented on datadog/fwprovider/data_source_datadog_app_builder_app.go
> +				Description: "Whether the app is published or unpublished. Published apps are available to other users. To ensure the app is accessible to the correct users, you also need to set a [Restriction P
Do you have any suggestions for how to change this description to reflect that? I was following the description in the Publish API doc https://docs.datadoghq.com/api/latest/app-builder/#publish-app

2025-03-21 18:13 UTC, GabeWM commented on datadog/fwprovider/data_source_datadog_app_builder_app.go
> +				Description: "Whether the app is published or unpublished. Published apps are available to other users. To ensure the app is accessible to the correct users, you also need to set a [Restriction P
I honestly don't just want to make you aware. AAA is working on changing this so hopefully will not be a problem in the future.

2025-03-21 18:14 UTC, tyffical commented on datadog/fwprovider/data_source_datadog_app_builder_app.go
> +				Description: "Whether the app is published or unpublished. Published apps are available to other users. To ensure the app is accessible to the correct users, you also need to set a [Restriction P
makes sense thanks!

2025-03-21 18:18 UTC, embeaken commented on datadog/fwprovider/resource_datadog_app_builder_app.go
> +	maps.Copy(configCopy, configJSON)
i don't think we should be modifying the config since that's basically the user input and messing with it could bypass TF's consistency rules. what's the reason it's needed here?

2025-03-21 18:19 UTC, embeaken commented on datadog/fwprovider/resource_datadog_app_builder_app.go
> +							if properties, ok := query["properties"].(map[string]interface{}); ok {
style: prefer `any` to `interface{}` (applies to the whole PR)

2025-03-21 18:21 UTC, GabeWM commented on datadog/fwprovider/resource_datadog_app_builder_app.go
> +	// if optional fields are not set, compute them from the app json
Ahh I see this is handled in modifyPlan. Nice.

2025-03-21 18:22 UTC, embeaken commented on datadog/fwprovider/resource_datadog_app_builder_app.go
> +	// Handle connection ID overrides
nit: comment doesn't seem to apply to the code

2025-03-21 18:23 UTC, GabeWM commented on datadog/fwprovider/resource_datadog_app_builder_app.go
> +	err = handleAppBuilderAppPublishUnpublish(r.Auth, response.Diagnostics, r.Api, &plan, appID)
Since these operations are not atomic in this case if an app is created successfully, but then the unpublished fails the app would remain created. Do we not want to do cleanup?

2025-03-21 18:24 UTC, GabeWM commented on datadog/fwprovider/resource_datadog_app_builder_app.go
> +	err = handleAppBuilderAppPublishUnpublish(r.Auth, response.Diagnostics, r.Api, &plan, appID)
Same question about atomic above although this does seem more difficult for update.

2025-03-21 18:25 UTC, GabeWM submitted a review, later dismissed
Wow, nice job!

2025-03-21 18:29 UTC, embeaken commented on datadog/fwprovider/resource_datadog_app_builder_app.go
> +	// Return error if any overrides weren't used
suggestion: this could just be a no-op instead of an error

2025-03-21 18:30 UTC, embeaken commented on datadog/fwprovider/resource_datadog_app_builder_app.go
> +				// if error is related to the app already being published, we can ignore it
ditto for this being a no-op instead of an error

2025-03-21 18:36 UTC, embeaken commented on datadog/tests/resource_datadog_app_builder_app_test.go
> +func testComplexAppBuilderApp(name string) string {
can you pull this from the example resource JSON file? i think that's the same as this and it would de-duplicate like 600 lines from this PR.

2025-03-21 18:47 UTC, tyffical commented on datadog/internal/customtypes/app_builder_app_json_string_value.go
> +		fieldsToKeep := []string{"components", "description", "name", "queries", "rootInstanceName"}
fields that would get excluded in this comparison would be "id", "favorite", "selfService", "tags", "connections", "deployment". these fields are included in the App JSON but don't make a difference when calling Create/Update endpoints

2025-03-24 17:19 UTC, tyffical commented on datadog/fwprovider/data_source_datadog_app_builder_app.go
> +			elementsMap[queryName] = ""
hm I can see that - I'll remove it

2025-03-24 17:24 UTC, tyffical commented on datadog/fwprovider/resource_datadog_app_builder_app.go
> +			"action_query_names_to_connection_ids": schema.MapAttribute{
that's a good point - makes sense to have override when it's specified and just build mapping otherwise

2025-03-24 17:51 UTC, tyffical commented on datadog/fwprovider/resource_datadog_app_builder_app.go
> +	err = handleAppBuilderAppPublishUnpublish(r.Auth, response.Diagnostics, r.Api, &plan, appID)
yeah update would be particularly difficult. i think i am fine with errors in publishing state b/c that can likely be resolved with another `apply` (as Ilya has commented below), and it's more important that an app is created / updated correctly than for it to be published/unpublished correctly (b/c the latter is easily fixed)

2025-03-24 17:56 UTC, tyffical commented on datadog/fwprovider/resource_datadog_app_builder_app.go
> +	maps.Copy(configCopy, configJSON)
ah good catch! this section of code is just copying for sake of comparison and not modifying the config itself. i think the config copies are leftover from previous iterations actually, since we end up only comparing the plan and state anyway. i'll remove the config stuff

2025-03-24 18:03 UTC, tyffical commented on datadog/fwprovider/resource_datadog_app_builder_app.go
> +	// Return error if any overrides weren't used
hm, I thought this would be helpful for users who may have accidentally misspelled a query name and want to quickly figure out why a connectionID wasn't changed as expected

2025-03-24 18:06 UTC, tyffical commented on datadog/fwprovider/resource_datadog_app_builder_app.go
> +					diags.AddError("error unpublishing app", string(body))
to clarify, do you mean we should ignore any errors related to unpublishing/publishing as long as the HTTP error body is readable? because this section of code already ignores specific errors like app already being disabled or published

```golang
				// if error is related to the app already being unpublished, we can ignore It
				if !strings.Contains(string(body), ErrAppAlreadyDisabled) {
					diags.AddError("error unpublishing app", string(body))
				} else {
					return nil
				}
```

2025-03-24 18:09 UTC, tyffical commented on datadog/fwprovider/resource_datadog_app_builder_app.go
> +	if err != nil {
i handled response diags in the helper func itself - i can change the return statement to a bool instead, like `fail` or `success`  just so we know whether to exit this TF CRUD operation early

2025-03-24 21:47 UTC, tyffical commented on datadog/fwprovider/resource_datadog_app_builder_app.go
> +	planAndStateEq, _ := customtypes.NewAppBuilderAppStringValue(string(planBytes)).StringSemanticEquals(ctx, customtypes.NewAppBuilderAppStringValue(string(stateBytes)))
i think it's probably possible to make it just a helper function but using a custom type makes more sense to me and keeps all that logic separate / away from this already really long file

2025-03-25 20:23 UTC, embeaken commented on datadog/fwprovider/resource_datadog_app_builder_app.go
> +					diags.AddError("error unpublishing app", string(body))
basically if i change the published flag in my TF config and run `terraform apply`, i'd want it to not give me an error if the publish state already matches what i put in my config. is that doable with the API?

2025-03-25 20:24 UTC, embeaken commented on datadog/fwprovider/resource_datadog_app_builder_app.go
> +	if err != nil {
ah ok

2025-03-25 20:27 UTC, embeaken commented on datadog/fwprovider/resource_datadog_app_builder_app.go
> +	planAndStateEq, _ := customtypes.NewAppBuilderAppStringValue(string(planBytes)).StringSemanticEquals(ctx, customtypes.NewAppBuilderAppStringValue(string(stateBytes)))
the custom type itself is a lot of boilerplate though. if you can have the comparison be a helper func (and you can put it somewhere else), that would get rid of the boilerplate and also would help anyone reading this code since they wouldn't have to also understand terraform custom types to work on it.

2025-03-25 20:28 UTC, embeaken commented on datadog/fwprovider/resource_datadog_app_builder_app.go
> +	// Return error if any overrides weren't used
sounds reasonable to me

2025-03-25 20:43 UTC, tyffical commented on datadog/fwprovider/resource_datadog_app_builder_app.go
> +					diags.AddError("error unpublishing app", string(body))
"if the publish state already matches what I put in my config" -> that's what happens when the App Builder API returns `ErrAlreadyDisabled` or `ErrDeploymentExists`, hence if we reach that error it will no-op and complete the CRUD operation normally (verified by manual and unit testing). I don't believe the other API errors have to do with publishing state already matching what we want

2025-03-25 20:45 UTC, tyffical commented on datadog/fwprovider/resource_datadog_app_builder_app.go
> +					diags.AddError("error unpublishing app", string(body))
hopefully the latest version makes this more clear:
```golang
				// if error is related to the app already being published, we can ignore it
				if strings.Contains(string(body), ErrDeploymentExists) {
					return true
				}
				diags.AddError("error publishing app", string(body))
				return false
```

2025-03-25 20:49 UTC, drichards-87 approved these changes

2025-03-26 08:42 UTC, fpighi commented on datadog/fwprovider/data_source_datadog_app_builder_app.go
> +	d.Api.Client.Cfg.AddDefaultHeader("X-Datadog-App-Builder-Source", "terraform")
Not sure if this is required. You could use `User-Agent` to identify requests being made by Terraform clients. I see a similar approach to yours is already used in `workflow_automation` resource/datasource, but that's the only occurrence.

Is `User-Agent` not enough for your use case?

2025-03-26 09:01 UTC, fpighi commented on docs/data-sources/app_builder_app.md
> +This data source retrieves the definition of an existing Datadog App from App Builder for use in other resources.
Is there any use case where customers might want to rely on this data source? Might be worth having an example here.

2025-03-26 15:08 UTC, embeaken submitted a review, later dismissed
:balloon:

2025-03-26 21:18 UTC, tyffical commented on docs/data-sources/app_builder_app.md
> +This data source retrieves the definition of an existing Datadog App from App Builder for use in other resources.
Does this suffice?
```text
This data source retrieves the definition of an existing Datadog App from App Builder for use in other resources, such as embedding Apps in Dashboards or Notebooks.
```

2025-03-26 21:18 UTC, tyffical commented on docs/data-sources/app_builder_app.md
> +This data source retrieves the definition of an existing Datadog App from App Builder for use in other resources.
Does this suffice?
```text
This data source retrieves the definition of an existing Datadog App from App Builder for use in other resources, such as embedding Apps in Dashboards or Notebooks.
```

2025-03-26 21:27 UTC, tyffical commented on datadog/fwprovider/data_source_datadog_app_builder_app.go
> +	d.Api.Client.Cfg.AddDefaultHeader("X-Datadog-App-Builder-Source", "terraform")
Ah yes I was copying the approach done in `workflow_automation`. As discussed offline, you are right that `User-Agent` should be enough to identify Terraform requests, and it's already included by default.

https://github.com/DataDog/terraform-provider-datadog/blob/master/datadog/fwprovider/framework_provider.go#L388-L394

https://github.com/DataDog/terraform-provider-datadog/blob/master/datadog/internal/utils/utils.go#L230-L236

2025-03-27 08:36 UTC, fpighi requested changes

2025-03-27 08:36 UTC, fpighi commented on datadog/fwprovider/data_source_datadog_app_builder_app.go
> +		Description: "This data source retrieves the definition of an existing Datadog App from App Builder for use in other resources, such as embedding Apps in Dashboards or Notebooks.",
```suggestion
		Description: "This data source retrieves the definition of an existing Datadog App from App Builder for use in other resources, such as embedding Apps in Dashboards.",
```
Notebooks doesn't exist as a Terraform resource.
As for dashboards, I'm ok with this example mentioned but customers will only be able to embed it when using the [dashboard JSON-based resource](https://registry.terraform.io/providers/DataDog/datadog/latest/docs/resources/dashboard_json), since the non-JSON one doesn't seem to support this right now.
I'm not sure this data source is extremely useful right now, but it could be kept for future integrations.
As long as the change in description is accepted, I'm happy to approve.

2025-03-27 14:06 UTC, embeaken approved these changes

2025-03-27 14:14 UTC, fpighi approved these changes

2025-03-27 15:13 UTC, GabeWM approved these changes

2025-03-27 15:24 UTC, oliverli approved these changes

2025-03-27 16:56 UTC, amaskara-dd commented
/merge

2025-03-27 17:49 UTC, amaskara-dd commented
/merge -c

2025-03-27 19:30 UTC, merged