Update vendor
DataDog/terraform-provider-datadog pull request #681
Opened 2020-10-05 14:34 UTC by vinckama

Vendor update to support new endpoints and attributes

2020-10-05 15:44 UTC, jirikuncar commented
/azp run

2020-10-05 15:50 UTC, jirikuncar approved these changes

2020-10-05 16:35 UTC, therve requested changes
Looks like the CI failure is legit.

2020-10-06 07:19 UTC, vinckama commented
That's a backward incompatibility, I'm going to fix that quickly on `api-spec`& each client

2020-10-07 08:58 UTC, therve commented
Opened #687

2020-10-07 08:58 UTC, closed without merging