[VIZZ-954] Update table widget definition and request
DataDog/terraform-provider-datadog pull request #686
Opened 2020-10-06 18:03 UTC by sighrobot

2020-10-06 18:25 UTC, therve commented
/azp run

2020-10-06 21:39 UTC, nmuesch reviewed
Quick question on the type

2020-10-06 21:39 UTC, nmuesch commented on datadog/resource_datadog_dashboard.go
> +			Type:     schema.TypeString,
Should this be a bool?

2020-10-06 21:39 UTC, nmuesch commented on datadog/resource_datadog_dashboard.go
> +	if v, ok := terraformDefinition["has_search_bar"].(datadogV1.TableWidgetHasSearchBar); ok && len(v) != 0 {
(If this winds up being a bool, we can probably remove the length check)

2020-10-06 22:55 UTC, nmuesch commented on datadog/resource_datadog_dashboard.go
> +			Type:     schema.TypeString,
Ahh ok thanks. You could do something like set a ValidateFunc with stringInSlice - https://github.com/hashicorp/terraform/blob/master/helper/validation/validation.go#L32 but I think its OK to just document the allowed fields too.

2020-10-09 07:49 UTC, therve requested changes
That looks good, can you tweak the documentation to mention the new field? Thanks.

2020-10-16 06:49 UTC, therve commented
/azp run

2020-10-16 06:49 UTC, therve approved these changes

2020-10-16 07:43 UTC, therve commented
/azp run

2020-10-16 09:02 UTC, merged