Validate palette enum
DataDog/terraform-provider-datadog pull request #794
Opened 2020-12-17 16:16 UTC by zippolyte

2020-12-18 10:32 UTC, therve submitted a review, later dismissed

2020-12-18 12:58 UTC, therve commented
/azp run

2020-12-18 15:51 UTC, romainberger submitted a review, later dismissed
LGTM for Synthetics 👍

2020-12-18 21:23 UTC, therve requested changes
Looks good, just a small but annoying comment.

2020-12-18 21:23 UTC, therve commented on datadog/resource_datadog_dashboard.go
> +	if err != nil {
With a little bit of elbow grease, I feel that we could define a wrapper function that you can directly assign to `ValidateFunc`. Seems non trivial. In the mean time, please inline the err check like `if _, err := ..; err != nil`

2020-12-28 13:33 UTC, therve approved these changes
That's awesome, one minor nit.

2020-12-28 13:33 UTC, therve commented on datadog/validators.go
> +		if err != nil {
Please inline the condition withe previous line.

2020-12-28 16:28 UTC, nmuesch approved these changes

2020-12-28 16:28 UTC, merged