[Synthetics] Add support for config variables
DataDog/terraform-provider-datadog pull request #807
Opened 2021-01-04 14:50 UTC by romainberger

Add support for `config_variable` for Synthetics tests.

To make things clearer, the `variable` has been renamed to `browser_variable` (keeping support for `variable` to avoid breaking changes). 

Based on https://github.com/DataDog/terraform-provider-datadog/pull/806

2021-01-04 17:19 UTC, therve requested changes
One minor change, and one question: couldn't we keep using `variable`, and use the right type depending on the test? The structures look very similar, it would make things slightly cleaner I think.

2021-01-04 17:19 UTC, therve commented on datadog/resource_datadog_synthetics_test_.go
> +					ValidateFunc: validation.StringInSlice(syntheticsConfigVariableTypes, false),
```suggestion
					ValidateFunc: validateEnumValue(datadogV1.NewSyntheticsConfigVariableTypeFromValue),
```

2021-01-05 10:15 UTC, romainberger commented
> couldn't we keep using `variable`, and use the right type depending on the test?

No, but I guess this means the documentation is not clear enough 😬 . 

- `config_variable` are used in tests configuration (for example in the test url), they can be used both for the API and browser tests.
- `browser_variable` are used in a browser test step. 

So for API tests you can only have `config_variable`, but for browser tests you can have both.

2021-01-05 15:14 UTC, nmuesch commented on datadog/resource_datadog_synthetics_test_.go
> +					Type:     schema.TypeString,
Can you add a description to each of these fields (in each schema)? We have an ongoing effort to ensure all fields have descriptions so we can work on autogenerating the terraform documentation - #798

2021-01-06 13:20 UTC, therve approved these changes

2021-01-06 17:07 UTC, merged