[Synthetics] Add support for global variables from test
DataDog/terraform-provider-datadog pull request #831
Opened 2021-01-11 10:13 UTC by romainberger

2021-01-11 13:52 UTC, sdeprez submitted a review, later dismissed

2021-01-11 14:35 UTC, romainberger commented
Please wait before merging, it needs a fix from https://github.com/DataDog/datadog-api-spec/pull/759

2021-01-12 09:32 UTC, romainberger commented
Good to merge when approved.

2021-01-12 11:20 UTC, therve requested changes
Some minor comments, otherwise looks good.

2021-01-12 11:20 UTC, therve commented on datadog/resource_datadog_synthetics_global_variable_test.go
> +       assertions = [
Should we use new assertion format in tests?

2021-01-12 11:20 UTC, therve commented on datadog/resource_datadog_synthetics_global_variable_test.go
> +           follow_redirects = true
If you can fix indentation that'd be great.

2021-01-12 11:20 UTC, therve commented on datadog/resource_datadog_synthetics_global_variable.go
> +			"parse_test_options": {
Please add description to all fields defined below.

2021-01-14 13:46 UTC, therve approved these changes

2021-01-14 14:25 UTC, therve commented
/azp run

2021-01-14 15:24 UTC, merged