Deprecated TypeMap complex fields
DataDog/terraform-provider-datadog pull request #853
Opened 2021-01-21 17:27 UTC by zippolyte

deprecate:
* `layout` typeMap
* `time` typeMap
* `compute` typeMap
* `sort` typeMap
* `search` typeMap

add:
* `widget_layout` typeList; maxItems: 1
* `live_span` typeString
* `compute_query` typeList; maxItems: 1
* `sort_query` typeList; maxItems: 1
* `search_query` typeString

2021-01-25 09:01 UTC, zippolyte commented
/azp run

2021-01-26 15:51 UTC, therve requested changes
Some minor changes. It looks good but a bit big, I hope we're not missing something.

2021-01-26 15:51 UTC, therve commented on datadog/resource_datadog_dashboard.go
> +func getWidgetNestedLiveSpanSchema() *schema.Schema {
Can you reuse `getWidgetNestedLiveSpanSchema`?

2021-01-26 15:51 UTC, therve commented on datadog/resource_datadog_dashboard.go
> +		Description:  "The timeframe to use when displaying the widget. One of `10m`, `30m`, `1h`, `4h`, `1d`, `2d`, `1w`.",
The description is outdated, can you add the missing values?

2021-01-26 16:01 UTC, zippolyte commented
I feel confident nothing is missing with the extensive per widget testing

2021-01-28 12:50 UTC, therve submitted a review, later dismissed

2021-01-29 09:04 UTC, zippolyte commented
/azp run

2021-02-01 13:38 UTC, jbenais approved these changes
Looks good to me, tested with old / new fields. Amazing work 🚀

2021-02-01 13:38 UTC, jbenais commented on datadog/resource_datadog_dashboard.go
> +			terraformDefinition["time"] = buildTerraformWidgetTime(*v)
nit: for consistency and clarity, should we replace the function name by `buildTerraformWidgetTimeDeprecated`

2021-02-01 13:54 UTC, zippolyte commented
/azp run

2021-02-02 08:26 UTC, zippolyte commented
/azp run

2021-02-02 08:41 UTC, therve approved these changes

2021-02-02 08:42 UTC, merged