Add security-monitoring team to codeowners
DataDog/terraform-provider-datadog pull request #869
Opened 2021-01-26 14:19 UTC by skarimo

Add security-monitoring team to CODEOWNERS file

2021-01-26 15:22 UTC, zippolyte submitted a review, later dismissed

2021-01-26 19:18 UTC, therve requested changes

2021-01-26 19:18 UTC, therve commented on .github/CODEOWNERS
> +docs/data-sources/security_monitoring     @DataDog/integrations-tools-and-libraries @DataDog/security-monitoring
```suggestion
docs/data-sources/security_monitoring     @DataDog/integrations-tools-and-libraries @DataDog/security-monitoring*
```

2021-02-10 15:25 UTC, therve approved these changes

2021-02-10 15:31 UTC, merged