Generate dashboard documentation
DataDog/terraform-provider-datadog pull request #886
Opened 2021-02-02 16:01 UTC by nmuesch

Generate documentation for dashboard resource + data source

This one is rather large, as it looks like each thing using a schema gets its own section in the docs. 
Aka each widget type is documented twice, once for its standard usage, and once for how to define it in a group widget

2021-02-02 16:50 UTC, zippolyte requested changes
Let's use the new fields instead of the deprecated ones in all the examples
i.e. 
- `time = { "live_span" = ... }` => `live_span = ...`
- `compute = { ... }` => `compute_query { ... }`
- `sort = { ... }` => `sort_query { ... }`
- `search = { "query" = ... }` => `search_query = ...`
- `layout  = { ... }` => `widget_layout { ... }`

2021-02-02 18:35 UTC, nmuesch commented
Thanks @zippolyte I updated the examples and quickly ran a `terraform plan` with it to confirm no deprecation messages on master. 

I also snuck in updating dashboard_list here since that example referenced deprecated fields.

2021-02-03 08:22 UTC, zippolyte approved these changes

2021-02-03 15:51 UTC, matt-miller-ddog approved these changes

2021-02-03 20:07 UTC, nmuesch commented
No go changes, only md+tf, going to merge. Thanks for the reviews!

2021-02-03 20:07 UTC, merged