remove unnecessary community client from resource test files
DataDog/terraform-provider-datadog pull request #908
Opened 2021-02-09 22:41 UTC by fanny-jiang

This PR removes unnecessary use of the community client from the Monitors and Metric Metadata resource test files and updates them to use the generated `datadog-go-api` client. It also includes some minor cleanup of unused parameters.

2021-02-09 23:25 UTC, skarimo reviewed
Small nits

2021-02-09 23:25 UTC, skarimo commented on datadog/resource_datadog_metric_metadata_test.go
> +func metadataExistsHelper(s *terraform.State, datadogV1Client *datadogV1.APIClient, authV1 context.Context) error {
```suggestion
func metadataExistsHelper(s *terraform.State, datadogClientV1 *datadogV1.APIClient, authV1 context.Context) error {
```
To maintain same format as rest of the repo

2021-02-09 23:25 UTC, skarimo commented on datadog/resource_datadog_metric_metadata_test.go
> +
```suggestion
```

2021-02-09 23:25 UTC, skarimo commented on datadog/resource_datadog_metric_metadata_test.go
> +		datadogV1Client := providerConf.DatadogClientV1
```suggestion
		datadogClientV1 := providerConf.DatadogClientV1
```

2021-02-09 23:25 UTC, skarimo commented on datadog/resource_datadog_metric_metadata_test.go
> +		if err := metadataExistsHelper(s, datadogV1Client, authV1); err != nil {
```suggestion
		if err := metadataExistsHelper(s, datadogClientV1, authV1); err != nil {
```
Here as well

2021-02-09 23:25 UTC, skarimo commented on datadog/resource_datadog_monitor_test.go
> +		datadogV1Client := providerConf.DatadogClientV1
```suggestion
		datadogClientV1 := providerConf.DatadogClientV1
```

2021-02-09 23:25 UTC, skarimo commented on datadog/resource_datadog_monitor_test.go
> +		if err := destroyHelper(s, datadogV1Client, authV1); err != nil {
```suggestion
		if err := destroyHelper(s, datadogClientV1, authV1); err != nil {
```

2021-02-09 23:25 UTC, skarimo commented on datadog/resource_datadog_monitor_test.go
> +		datadogV1Client := providerConf.DatadogClientV1
```suggestion
		datadogClientV1 := providerConf.DatadogClientV1
```

2021-02-09 23:25 UTC, skarimo commented on datadog/resource_datadog_monitor_test.go
> +		if err := existsHelper(s, datadogV1Client, authV1); err != nil {
```suggestion
		if err := existsHelper(s, datadogClientV1, authV1); err != nil {
```

2021-02-09 23:25 UTC, skarimo commented on datadog/resource_datadog_monitor_test.go
> +func existsHelper(s *terraform.State, datadogV1Client *datadogV1.APIClient, authV1 context.Context) error {
```suggestion
func existsHelper(s *terraform.State, datadogClientV1 *datadogV1.APIClient, authV1 context.Context) error {
```

2021-02-09 23:25 UTC, skarimo commented on datadog/resource_datadog_monitor_test.go
> +		_, _, err := datadogV1Client.MonitorsApi.GetMonitor(authV1, i).Execute()
```suggestion
		_, _, err := datadogClientV1.MonitorsApi.GetMonitor(authV1, i).Execute()
```

2021-02-09 23:25 UTC, skarimo commented on datadog/resource_datadog_monitor_test.go
> +
```suggestion
```

2021-02-10 08:04 UTC, zippolyte requested changes
Just a few small changes to have better error message when using the go client

2021-02-10 08:04 UTC, zippolyte commented on datadog/resource_datadog_metric_metadata_test.go
> +			return fmt.Errorf("received an error retrieving metric_metadata %s", err)
```suggestion
			return translateClientError(err, "error retrieving metric_metadata")
```

2021-02-10 08:04 UTC, zippolyte commented on datadog/resource_datadog_monitor_test.go
>  			return fmt.Errorf("received an error retrieving monitor %s", err)
```suggestion
			return translateClientError(err, "error retrieving monitor")
```

2021-02-10 08:04 UTC, zippolyte commented on datadog/resource_datadog_monitor_test.go
>  			return fmt.Errorf("received an error retrieving monitor %s", err)
```suggestion
			return translateClientError(err, "error retrieving monitor")
```

2021-02-10 15:47 UTC, zippolyte approved these changes

2021-02-11 19:54 UTC, skarimo approved these changes

2021-02-11 19:54 UTC, skarimo commented
/azp run

2021-02-12 19:57 UTC, merged