Update 3rd Party License file and add check to CI
DataDog/terraform-provider-datadog pull request #929
Opened 2021-02-16 21:27 UTC by nmuesch

* Updates the 3rd party csv file to note all the deps we have in go.sum
* Adds a new script `license-check.sh`, essentially a copy from the datadog-api-client-go with a change from `echo` -> `printf`
  * Run the script via `make license-check` and add this to the github action CI

2021-02-16 21:29 UTC, jeremy-lq requested changes
These should be updated to SPDX identifiers

2021-02-16 21:39 UTC, jeremy-lq approved these changes

2021-02-16 22:15 UTC, nmuesch commented
/azp run

2021-02-17 07:58 UTC, zippolyte approved these changes

2021-02-17 14:55 UTC, merged