Add support for dashboard json resource
DataDog/terraform-provider-datadog pull request #950
Opened 2021-02-24 23:13 UTC by skarimo

2021-03-01 20:45 UTC, therve reviewed
That looks great, some questions around and minor comments.

2021-03-01 20:45 UTC, therve commented on datadog/resource_datadog_dashboard_json.go
> +	path := "/api/v1/dashboard/" + d.Id()
Can you create a constant with that path?

2021-03-01 20:45 UTC, therve commented on datadog/tests/resource_datadog_dashboard_json_test.go
> +	t.Parallel()
Please put that first in the test, that avoids creating providers in memory.

2021-03-01 20:45 UTC, therve commented on datadog/tests/resource_datadog_dashboard_json_test.go
> +		CheckDestroy: checkDashboardDestroy(accProvider),
👍

2021-03-01 20:45 UTC, therve commented on datadog/tests/resource_datadog_dashboard_json_test.go
> +	t.Parallel()
Same here.

2021-03-01 20:45 UTC, therve commented on datadog/resource_datadog_dashboard_json.go
> +	test, err := utils.NormalizeJSONorYamlString(d.Get("dashboard").(string))
That's an interesting approach. FWIW my thinking was more to check if calling `jsonencode(yamldecode(data)` would work. Do you think that would simplify the code?

2021-03-01 20:45 UTC, therve commented on datadog/resource_datadog_dashboard_json.go
> +	test, err := utils.NormalizeJSONorYamlString(d.Get("dashboard").(string))
Also let's name the variable something else than `test`.

2021-03-09 13:01 UTC, zippolyte requested changes
Just a couple of comments, looks great overall

2021-03-09 13:01 UTC, zippolyte commented on datadog/resource_datadog_dashboard_json.go
> +				Description: "The JSON or YAML formatted definition of the Dashboard.",
Wait, is yaml supported natively ? How does that work 🤯

2021-03-09 15:32 UTC, zippolyte commented on datadog/tests/resource_datadog_dashboard_json_test.go
> +func TestAccDatadogDashboardJSON_BasicTimeboard(t *testing.T) {
Yeah we do, but I thought this was changed by Thomas when he added the linter.

2021-03-09 15:44 UTC, therve commented on datadog/tests/resource_datadog_dashboard_json_test.go
> +func TestAccDatadogDashboardJSON_BasicTimeboard(t *testing.T) {
It doesn't fail for public names, so `Test_Basic` is allowed, not `test_basic`.

2021-03-10 16:43 UTC, zippolyte approved these changes

2021-03-10 17:00 UTC, skarimo commented
/azp run

2021-03-10 19:15 UTC, merged