Upgrade to terraform sdk v2
DataDog/terraform-provider-datadog pull request #972
Opened 2021-03-08 14:52 UTC by skarimo

This PR updates the terraform provider to use terraform SDK v2

2021-03-09 14:19 UTC, zippolyte requested changes
A few comments. Once they are addressed, I think we can merge to the v2 branch, and iterate from here.

Also, do cassette really need rerecording ? Seems to me every change is internal, and shouldn't impact the requests made, isn't it ?

2021-03-09 14:19 UTC, zippolyte commented on datadog/resource_datadog_timeboard.go
>  package datadog
delete that entirely

2021-03-09 14:19 UTC, zippolyte commented on datadog/tests/data_source_datadog_dashboard_list_test.go
> -				ExpectNonEmptyPlan: true,
is this not applicable anymore ?

2021-03-09 14:19 UTC, zippolyte commented on datadog/tests/data_source_datadog_monitor_test.go
> -		// this is the way to get them.
Are typeSet nice now with v2 ?

2021-03-09 14:19 UTC, zippolyte commented on datadog/tests/resource_datadog_timeboard_test.go
>  	"github.com/terraform-providers/terraform-provider-datadog/datadog"
let's remove

2021-03-09 14:19 UTC, zippolyte commented on datadog/tests/resource_datadog_screenboard_test.go
let's remove

2021-03-09 15:24 UTC, skarimo commented on datadog/data_source_datadog_monitor.go
> -				MaxItems:    1,
tf plugin sdk V2 has more robust validations: https://www.terraform.io/docs/extend/guides/v2-upgrade-guide.html#stronger-validation-for-helper-schema-schema-computed-fields

Setting `MaxItems` on `Computed` fields is no longer supported and will throw an error

2021-03-09 15:30 UTC, zippolyte commented on datadog/data_source_datadog_monitor.go
> -				MaxItems:    1,
Ah true, didn't realise it was a datasource

2021-03-09 15:30 UTC, skarimo commented on datadog/provider.go
> +func Provider() func() *schema.Provider {
Good catch thanks!

2021-03-09 15:44 UTC, skarimo commented on datadog/resource_datadog_dashboard.go
> -	})
Any reason this was added here? My thought process was we receive the created dashboard from the Create api call and can use that to set state, reducing number of API calls: https://github.com/DataDog/terraform-provider-datadog/blob/master/datadog/resource_datadog_dashboard.go#L128

2021-03-09 15:59 UTC, skarimo commented on datadog/resource_datadog_monitor.go
> +	time.Sleep(3 * time.Second)
Yes thanks!

2021-03-09 16:05 UTC, skarimo commented on datadog/resource_datadog_service_level_objective.go
> +				return fmt.Errorf("error finding monitor to add to SLO: %s", err.Error())
debug remnant as well. Thanks

2021-03-09 16:40 UTC, zippolyte commented on datadog/tests/data_source_datadog_monitor_test.go
> -		// this is the way to get them.
sweet

2021-03-11 08:37 UTC, zippolyte approved these changes
Looks good, I think we should merge this, and keep working on that branch to polish things if needed

2021-03-11 15:17 UTC, merged